### ISSUE TITLE
Missing instructions on how to use

### ISSUE THREAD

**Issue by brunoborges** [oracle/apps-mobile-ui-kit#1]
Hi,

The README states `Find below instructions for using the MAF RDK with JDeveloper.` but there aren't instructions after that.

**Comment by lancysilveira** [comment]
Hi Bruno,
Thank you for the note. I have updated README.md section 'Instructions for using the RDK' to point to the included Technical eBook, which has an entire section on running the sample application.
Regards,

**Comment by brunbennett** [comment]
Thanks
